<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
<!--
  <div>
    <label><?php echo $this->__('BitPay Transaction ID') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('BitPay Transaction ID') ?>" name="payment[bitpay_transactionid]" value="<?php echo $this->htmlEscape($this->getInfoData('bitpay_transactionid')) ?>" />
    </span>
  </div>
  -->
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
